---
- name: Instalar e Configurar Docker
  hosts: docker-vm-01, docker-vm-02, docker-vm-03, docker-vm-04, docker-vm-05, docker-vm-06, docker-vm-07, docker-vm-08, docker-vm-09, docker-vm-10
  become: yes
  tasks:
    - name: Instalar pacotes necessários
      yum:
        name: yum-utils
        state: present

    - name: Adicionar repositório do Docker
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        warn: false

    - name: Instalar Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Adicionar usuário ao grupo docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Habilitar serviço Docker
      systemd:
        name: docker
        enabled: yes
        state: started
