---
- name: Instalar Docker e configurar serviço
  hosts: all
  become: yes
  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Instalar pacotes necessários
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Adicionar repositório do Docker
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
        state: present
      when: ansible_os_family == "Debian"

    - name: Importar chave do repositório Docker
      apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        state: present
      when: ansible_os_family == "Debian"

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == "Debian"

    - name: Garantir que o serviço Docker está em execução
      service:
        name: docker
        state: started
        enabled: yes

    - name: Adicionar usuário ao grupo docker
      user:
        name: "{{ ansible_env.USER }}"
        group: docker
        append: yes

    - name: Configurar agendamento do serviço Docker
      cron:
        name: "Iniciar Docker às 14:00"
        minute: "0"
        hour: "14"
        job: "/usr/bin/systemctl restart docker"
        state: present

  handlers:
    - name: Reiniciar Docker
      service:
        name: docker
        state: restarted

