# Use a imagem oficial do nginx como base
FROM nginx

# Copie o arquivo de configuração personalizado do nginx para o container
COPY nginx.conf /etc/nginx/nginx.conf

# Exponha a porta 80 para o nginx
EXPOSE 80